# my setting
future: true

# git settings
lsi: false
safe: true
incremental: false
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Site settings
title: GreenWinter Blog
SEOTitle: 绿冬的博客 | Dong Lyu's Blog
header-img: img/home-bg.jpg
email: dlv19@fudan.edu.cn
description: "贴贴使人快乐"
keyword: "blog"
url: "https://donlv1997.github.io"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username: "银色秋千"
zhihu_username: "lu-zhi-dong-64-3"
github_username:    donlv1997
#twitter_username:  huxpro
#facebook_username:  huxpro



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: donlv1997

# Duoshuo settings
# duoshuo_username: huxblog
# Share component is depend on Comment so we can NOT use share only.
# duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: e6a13a93288708d3dee567a97fbfb3df
# Google Analytics
ga_track_id: 'UA-180536439-1'            # Format: UA-xxxxxx-xx
ga_domain: donlv1997.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "大家都好厉害哦，我只能边摸边发出感慨"
sidebar-avatar: /img/head_picture.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "lab369",
        href: "http://lab.zhuzhuguowang.cn:36900/dokuwiki/doku.php/start"
    },
    {
        title: "xnchen blog",
        href: "https://kyokoning.github.io"
    }
]
